name: build

on:
  workflow_run:
    workflows:
      - release-to-maven-central-tag
    types:
      - requested
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "${{ github.event.workflow_run}}"