name: check-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Revert changes checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check successful commit ID
      if: always()
      uses: grace-matson/check-build-successful@test-branch
      id: check
      with:
        token: ${{ github.token }}
        branch: ${{ github.ref_name }}
        workflow: "build"
        verify: true
    - name: Print output
      run: echo ${{steps.check.outputs.check}}
