name: hello

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('failing on purpose')

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    if: ${{ failure()}}
    steps:
      - run: echo "Hello world"

      # Runs a single command using the runners shell
#       - name: Hello world 
#         run: echo Hello, world!
#       - name: Gcloud command check
#         run: gcloud auth list
#       - name: Check Project
#         run: gcloud config list project
      # - run: |
      #     chmod +x ./.github/scripts/hello.sh
      #     ./.github/scripts/hello.sh
#
