name: test

on:
  workflow_dispatch:

concurrency:
  group: test
  
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Revert changes checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha::$(git rev-parse --short HEAD~1)"

    - name: Revert changes
      if: always()
      run: |
        git read-tree -u --reset ${{ steps.vars.outputs.sha }}
        git status
        git add .
        git commit -m "Trying to revert "

    - name: Create Pull Request for Revert
      if: always()
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        token: ${{ github.token }}
        title: 'Automated PR'
        body: |
          This PR is to revert from commit ${{github.sha}} to ${{ steps.vars.outputs.sha }} 
          because workflow ${{ github.workflow	}} failed on run ${{github.run_id}}
        branch: revert-${{github.run_id}}
        delete-branch: true
