name: unit_test

on:
  pull_request:
jobs:
  check:
    runs-on: new-runner
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check payload
      run : echo "${{ toJson(github.event) }}"

    - name: Get list of changed files
      uses: tj-actions/changed-files@v23.2
      if: always()
      id: list
    - name: echo
      run: |
        echo ${{ steps.list.outputs.added_files }}
        echo ${{ steps.list.outputs.modified_files }}
    - name: Log list and search for necessary files
      if: always()
      env:
        ADDED_LIST: ${{ steps.list.outputs.added_files }}
        MODIFIED_LIST: ${{ steps.list.outputs.modified_files }}
      run: python3 ./.github/scripts/check.py




