name: unit_test

on:
  pull_request:
jobs:
  check:
    runs-on: new-runner
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check payload
      run : echo "${{ toJson(github.event) }}"

    - name: Get list of changed files
      uses: grace-matson/compare-basehead-commits@main
      if: always()
      id: list
      with:
        format: 'json'
    - name: Log list
      if: always()
      env:
        ADDED_LIST: ${{ steps.list.outputs.added }}
        MODIFIED_LIST: ${{ steps.list.outputs.modified }}
      run: python3 ./.github/scripts/lis.py

