name: check-build

on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check payload
      run : echo ${{ github.event }}
